name: Release Electron App

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: |
          Release type - 选择版本发布类型：
          • patch: 补丁版本，修复 bug (例: 0.5.0 → 0.5.1)
          • minor: 次要版本，新增功能 (例: 0.5.0 → 0.6.0)
          • major: 主要版本，破坏性更新 (例: 0.5.0 → 1.0.0)
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      pre-release:
        description: |
          Create as pre-release - 是否创建为预发布版本
          • true: 预发布版本，不会推送给所有用户
          • false: 正式发布版本，会推送给所有用户
        required: false
        default: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.ANT_CHAT_RELEASE }}
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        
    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
        
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
          
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Create release commit
      run: |
        # Create a conventional commit for the release based on selected type
        if [ "${{ github.event.inputs.release-type }}" = "patch" ]; then
          git commit --allow-empty -m "fix: release version [skip ci]"
        elif [ "${{ github.event.inputs.release-type }}" = "minor" ]; then
          git commit --allow-empty -m "feat: release version [skip ci]"
        elif [ "${{ github.event.inputs.release-type }}" = "major" ]; then
          git commit --allow-empty -m "feat: major release version [skip ci]\n\nBREAKING CHANGE: Major version update"
        fi
        
    - name: Push release commit
      run: |
        git push origin main
        
    - name: Run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.ANT_CHAT_RELEASE }}
        GH_TOKEN: ${{ secrets.ANT_CHAT_RELEASE }}
      run: pnpm release

  build:
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        node-version: [20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false
        
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
        
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
          
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Build app (Windows)
      if: matrix.os == 'windows-latest'
      run: pnpm build:win
      
    - name: Build app (macOS)
      if: matrix.os == 'macos-latest'
      run: pnpm build:mac
      
    - name: Upload artifacts (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: |
          packages/electron/release/**
          !packages/electron/release/**/*-unpacked/
        
    - name: Upload artifacts (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: |
          packages/electron/release/**
          !packages/electron/release/**/*-unpacked/

  upload-release:
    needs: [release, build]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.ANT_CHAT_RELEASE }}
        
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Get latest tag
      id: get-tag
      run: |
        TAG=$(git describe --tags --abbrev=0)
        echo "tag=$TAG" >> $GITHUB_OUTPUT
      
    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          windows-build/**/*.exe
          windows-build/**/*.blockmap
          macos-build/**/*.dmg
          macos-build/**/*.zip
        prerelease: ${{ github.event.inputs.pre-release == 'true' }}
        tag_name: ${{ steps.get-tag.outputs.tag }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.ANT_CHAT_RELEASE }}
